name: kaggle-plankton
channels:
  - defaults
dependencies:
  - python=3.6.9
  - black=19.10b0
  - numpy=1.18.5
  - pandas=1.1.1
  - pip=19.0.3
  - pillow=8.1.0
  - pip:
    - pylint==2.3.1
    - scikit-image==0.15.0
    - tensorflow==2.4.1
