from pathlib import Path

WORKING_DIR = Path.cwd()  # Change this to one level above src folder
DATA_DIR = WORKING_DIR / "data"
TRAIN_DIR = DATA_DIR / "train"
VAL_DIR = DATA_DIR / "val"
TEST_DIR = DATA_DIR / "val"
WEIGHTS_DIR = WORKING_DIR / "weights"

TARGET_SIZE = (224, 224)
BATCH_SIZE = 32
INPUT_SHAPE = TARGET_SIZE + (3,)
LR = 0.001
DROPOUT = 0.5
N_EPOCH = 10

DEFAULT_CLASSES = [
    "heteropod",
    "invertebrate_larvae_other_B",
    "fish_larvae_very_thin_body",
    "hydromedusae_liriope",
    "hydromedusae_narco_dark",
    "hydromedusae_typeE",
    "hydromedusae_other",
    "fish_larvae_deep_body",
    "trichodesmium_multiple",
    "siphonophore_physonect_young",
    "hydromedusae_haliscera_small_sideview",
    "fish_larvae_leptocephali",
    "pteropod_theco_dev_seq",
    "stomatopod",
    "echinopluteus",
    "hydromedusae_typeF",
    "protist_star",
    "siphonophore_calycophoran_sphaeronectes_young",
    "hydromedusae_typeD_bell_and_tentacles",
    "euphausiids_young",
    "echinoderm_seacucumber_auricularia_larva",
    "siphonophore_partial",
    "hydromedusae_bell_and_tentacles",
    "echinoderm_larva_pluteus_brittlestar",
    "siphonophore_calycophoran_sphaeronectes_stem",
    "trochophore_larvae",
    "siphonophore_calycophoran_rocketship_adult",
    "jellies_tentacles",
    "hydromedusae_aglaura",
    "polychaete",
    "ephyra",
    "shrimp_sergestidae",
    "shrimp-like_other",
    "hydromedusae_solmundella",
    "tunicate_doliolid",
    "unknown_blobs_and_smudges",
    "invertebrate_larvae_other_A",
    "euphausiids",
    "siphonophore_calycophoran_sphaeronectes",
    "siphonophore_other_parts",
    "hydromedusae_shapeA",
    "fish_larvae_medium_body",
    "echinoderm_larva_pluteus_urchin",
    "pteropod_triangle",
    "unknown_sticks",
    "hydromedusae_shapeB",
    "hydromedusae_h15",
    "protist_dark_center",
    "hydromedusae_shapeA_sideview_small",
    "shrimp_caridean",
    "echinoderm_larva_pluteus_early",
    "unknown_unclassified",
    "diatom_chain_tube",
    "protist_other",
    "radiolarian_colony",
    "hydromedusae_haliscera",
    "echinoderm_larva_seastar_brachiolaria",
    "shrimp_zoea",
    "hydromedusae_typeD",
    "trichodesmium_puff",
    "tunicate_salp",
    "hydromedusae_narcomedusae",
    "protist_noctiluca",
    "diatom_chain_string",
    "fecal_pellet",
    "echinoderm_larva_seastar_bipinnaria",
    "tunicate_partial",
    "hydromedusae_sideview_big",
    "fish_larvae_thin_body",
    "tunicate_doliolid_nurse",
    "tornaria_acorn_worm_larvae",
    "tunicate_salp_chains",
    "hydromedusae_solmaris",
    "protist_fuzzy_olive",
    "radiolarian_chain",
    "siphonophore_calycophoran_rocketship_young",
    "trichodesmium_tuft",
    "echinoderm_larva_pluteus_typeC",
    "pteropod_butterfly",
    "fish_larvae_myctophids",
    "trichodesmium_bowtie",
    "hydromedusae_partial_dark",
    "hydromedusae_narco_young",
    "siphonophore_calycophoran_abylidae",
    "siphonophore_physonect",
    "acantharia_protist",
    "acantharia_protist_big_center",
    "acantharia_protist_halo",
    "amphipods",
    "appendicularian_fritillaridae",
    "appendicularian_s_shape",
    "appendicularian_slight_curve",
    "appendicularian_straight",
    "artifacts",
    "artifacts_edge",
    "chaetognath_non_sagitta",
    "chaetognath_other",
    "chaetognath_sagitta",
    "chordate_type1",
    "copepod_calanoid",
    "copepod_calanoid_eggs",
    "copepod_calanoid_eucalanus",
    "copepod_calanoid_flatheads",
    "copepod_calanoid_frillyAntennae",
    "copepod_calanoid_large",
    "copepod_calanoid_large_side_antennatucked",
    "copepod_calanoid_octomoms",
    "copepod_calanoid_small_longantennae",
    "copepod_cyclopoid_copilia",
    "copepod_cyclopoid_oithona",
    "copepod_cyclopoid_oithona_eggs",
    "copepod_other",
    "crustacean_other",
    "ctenophore_cestid",
    "ctenophore_cydippid_no_tentacles",
    "ctenophore_cydippid_tentacles",
    "ctenophore_lobate",
    "decapods",
    "detritus_blob",
    "detritus_filamentous",
    "detritus_other",
]

